/**
 * Token Listing Service
 *
 * Implements the Liquidity-Locked Listing System for Lunex DEX.
 * The system automatically creates the pool, deposits liquidity,
 * and locks LP tokens on behalf of the user.
 *
 * Tiers:
 *   BASIC    (1): 1 000 LUNES fee | 10 000 LUNES min liq | 90 days lock
 *   VERIFIED (2): 5 000 LUNES fee | 25 000 LUNES min liq | 120 days lock
 *   FEATURED (3): 20 000 LUNES fee | 50 000 LUNES min liq | 180 days lock
 *
 * Fee distribution: 20% staking · 50% team revenue · 30% rewards pool
 */

import prisma from '../db'
import { ListingTier, ListingStatus, LockStatus } from '@prisma/client'
import { log } from '../utils/logger'
import { registerToken } from './tokenRegistryService'

// ── Tier parameters ───────────────────────────────────────────────

export const TIER_CONFIG = {
  BASIC: {
    tier:         ListingTier.BASIC,
    tierNumber:   1,
    label:        'Basic',
    listingFee:   1_000,         // LUNES
    minLunesLiq:  10_000,        // LUNES (min 10k)
    lockDays:     90,
    lockMs:       90 * 24 * 60 * 60 * 1000,
    badge:        null,
    description:  'Entry-level listing. Token visible in search.',
  },
  VERIFIED: {
    tier:         ListingTier.VERIFIED,
    tierNumber:   2,
    label:        'Verified',
    listingFee:   5_000,
    minLunesLiq:  25_000,        // LUNES (min 25k)
    lockDays:     120,
    lockMs:       120 * 24 * 60 * 60 * 1000,
    badge:        'verified',
    description:  'Verified badge, trending section, DEX highlight.',
  },
  FEATURED: {
    tier:         ListingTier.FEATURED,
    tierNumber:   3,
    label:        'Featured',
    listingFee:   20_000,
    minLunesLiq:  50_000,        // LUNES (min 50k)
    lockDays:     180,
    lockMs:       180 * 24 * 60 * 60 * 1000,
    badge:        'featured',
    description:  'Home highlight, campaigns, reward incentives.',
  },
} as const

export type TierKey = keyof typeof TIER_CONFIG

// Fee split (basis points)
const BPS_STAKING  = 2000 // 20% → staking pool
const BPS_TREASURY = 5000 // 50% (team revenue)
const BPS_REWARDS  = 3000 // 30%

export function calcFeeDistribution(fee: number) {
  return {
    staking:  Math.floor((fee * BPS_STAKING)  / 10_000),
    treasury: Math.floor((fee * BPS_TREASURY) / 10_000),
    rewards:  Math.floor((fee * BPS_REWARDS)  / 10_000),
  }
}

// ── Types ─────────────────────────────────────────────────────────

export type CreateListingInput = {
  ownerAddress:    string
  tokenAddress:    string
  tokenName:       string
  tokenSymbol:     string
  tokenDecimals?:  number
  tier:            TierKey
  lunesLiquidity:  string        // decimal string — LUNES to deposit
  tokenLiquidity:  string        // decimal string — TOKEN to deposit
  description?:    string
  website?:        string
  // Auto-generated by pool creation (not user-provided)
  pairAddress?:    string
  lpTokenAddress?: string
  lpAmount?:       string
  txHash?:         string
  logoURI?:        string
}

export type ListingWithLock = Awaited<ReturnType<typeof getListingById>>

// ── Service functions ─────────────────────────────────────────────

export async function getAllTierConfigs() {
  return Object.values(TIER_CONFIG).map((c) => ({
    tier:          c.tier,
    tierNumber:    c.tierNumber,
    label:         c.label,
    listingFee:    c.listingFee,
    minLunesLiq:   c.minLunesLiq,
    lockDays:      c.lockDays,
    badge:         c.badge,
    description:   c.description,
    feeDistribution: calcFeeDistribution(c.listingFee),
  }))
}

export async function createListing(input: CreateListingInput) {
  const cfg = TIER_CONFIG[input.tier]
  if (!cfg) throw new Error(`Invalid tier: ${input.tier}`)

  const lunesLiq = parseFloat(input.lunesLiquidity)
  if (isNaN(lunesLiq) || lunesLiq < cfg.minLunesLiq) {
    throw new Error(
      `Insufficient LUNES liquidity for ${cfg.label} tier. ` +
      `Required: ${cfg.minLunesLiq} LUNES, provided: ${lunesLiq} LUNES`,
    )
  }

  const existing = await prisma.tokenListing.findUnique({
    where: { tokenAddress: input.tokenAddress },
  })
  if (existing) {
    throw new Error(`Token ${input.tokenAddress} is already listed`)
  }

  const unlockAt = new Date(Date.now() + cfg.lockMs)

  // LP fields are auto-generated: pool creation happens on-chain
  const lpTokenAddress = input.lpTokenAddress || 'pending-pool-creation'
  const lpAmount = input.lpAmount || '0'
  const pairAddress = input.pairAddress || 'pending-pool-creation'

  const listing = await prisma.tokenListing.create({
    data: {
      ownerAddress:   input.ownerAddress,
      tokenAddress:   input.tokenAddress,
      tokenName:      input.tokenName,
      tokenSymbol:    input.tokenSymbol,
      tokenDecimals:  input.tokenDecimals ?? 18,
      pairAddress,
      tier:           cfg.tier,
      status:         ListingStatus.PENDING,
      listingFee:     cfg.listingFee.toFixed(18),
      lunesLiquidity: input.lunesLiquidity,
      tokenLiquidity: input.tokenLiquidity,
      lpAmount,
      txHash:         input.txHash,
      logoURI:        input.logoURI ?? null,
      liquidityLock: {
        create: {
          ownerAddress:   input.ownerAddress,
          pairAddress,
          lpTokenAddress,
          lpAmount,
          lunesLocked:    input.lunesLiquidity,
          tokenLocked:    input.tokenLiquidity,
          tier:           cfg.tier,
          status:         LockStatus.LOCKED,
          unlockAt,
        },
      },
    },
    include: { liquidityLock: true },
  })

  log.info(
    { listingId: listing.id, token: input.tokenSymbol, tier: cfg.label },
    '[Listing] Token listing created',
  )

  const feeDist = calcFeeDistribution(cfg.listingFee)
  log.info(
    { ...feeDist, totalFee: cfg.listingFee },
    '[Listing] Fee distribution',
  )

  return listing
}

export type ActivateListingInput = {
  onChainListingId?: number
  pairAddress?:      string
  lpTokenAddress?:   string
  lpAmount?:         string
  txHash?:           string
}

export async function activateListing(listingId: string, input: ActivateListingInput = {}) {
  const listing = await prisma.tokenListing.update({
    where: { id: listingId },
    data: {
      status:          ListingStatus.ACTIVE,
      onChainListingId: input.onChainListingId,
      pairAddress:     input.pairAddress || undefined,
      lpAmount:        input.lpAmount || undefined,
      txHash:          input.txHash || undefined,
      verifiedAt:      new Date(),
    },
    include: { liquidityLock: true },
  })

  // Update the liquidity lock with real on-chain pool data
  if (listing.liquidityLock && (input.pairAddress || input.lpTokenAddress || input.lpAmount)) {
    await prisma.liquidityLock.update({
      where: { id: listing.liquidityLock.id },
      data: {
        ...(input.pairAddress    ? { pairAddress:    input.pairAddress }    : {}),
        ...(input.lpTokenAddress ? { lpTokenAddress: input.lpTokenAddress } : {}),
        ...(input.lpAmount       ? { lpAmount:       input.lpAmount }       : {}),
      },
    })
  }

  log.info(
    { listingId, pairAddress: input.pairAddress || 'unchanged' },
    '[Listing] Listing activated',
  )

  // Auto-register token in registry
  try {
    await registerToken({
      address:    listing.tokenAddress,
      symbol:     listing.tokenSymbol,
      name:       listing.tokenName,
      decimals:   listing.tokenDecimals,
      logoURI:    listing.logoURI ?? undefined,
      isVerified: listing.tier !== ListingTier.BASIC,
      source:     'LISTING',
      listingId:  listing.id,
    })
  } catch (regErr) {
    log.warn({ listingId, err: regErr }, '[Listing] TokenRegistry auto-register failed')
  }

  return listing
}

export async function rejectListing(listingId: string) {
  const listing = await prisma.tokenListing.update({
    where: { id: listingId },
    data: { status: ListingStatus.REJECTED },
  })
  log.warn({ listingId }, '[Listing] Listing rejected by admin')
  return listing
}

export async function getListingById(listingId: string) {
  return prisma.tokenListing.findUnique({
    where: { id: listingId },
    include: { liquidityLock: true },
  })
}

export async function getListingByToken(tokenAddress: string) {
  return prisma.tokenListing.findUnique({
    where: { tokenAddress },
    include: { liquidityLock: true },
  })
}

export async function getListings(params: {
  tier?:   ListingTier
  status?: ListingStatus
  limit?:  number
  offset?: number
}) {
  const { tier, status, limit = 50, offset = 0 } = params
  return prisma.tokenListing.findMany({
    where: {
      ...(tier   ? { tier }   : {}),
      ...(status ? { status } : {}),
    },
    include: { liquidityLock: true },
    orderBy: { createdAt: 'desc' },
    take:    limit,
    skip:    offset,
  })
}

export async function getOwnerListings(ownerAddress: string) {
  return prisma.tokenListing.findMany({
    where:   { ownerAddress },
    include: { liquidityLock: true },
    orderBy: { createdAt: 'desc' },
  })
}

export async function processExpiredLocks() {
  const now = new Date()
  const expiredLocks = await prisma.liquidityLock.findMany({
    where: {
      status:   LockStatus.LOCKED,
      unlockAt: { lte: now },
    },
    include: { listing: true },
  })

  for (const lock of expiredLocks) {
    await prisma.liquidityLock.update({
      where: { id: lock.id },
      data:  { status: LockStatus.UNLOCKED },
    })
    log.info(
      { lockId: lock.id, owner: lock.ownerAddress, token: lock.listing.tokenSymbol },
      '[Listing] Lock expired — owner can now withdraw LP tokens',
    )
  }

  return expiredLocks.length
}

export async function withdrawLock(lockId: string, ownerAddress: string, txHash?: string) {
  const lock = await prisma.liquidityLock.findUnique({ where: { id: lockId } })
  if (!lock) throw new Error('Lock not found')
  if (lock.ownerAddress !== ownerAddress) throw new Error('Not the lock owner')
  if (lock.status === LockStatus.WITHDRAWN) throw new Error('Already withdrawn')
  if (lock.status === LockStatus.LOCKED && lock.unlockAt > new Date()) {
    throw new Error(`Lock expires at ${lock.unlockAt.toISOString()}`)
  }

  return prisma.liquidityLock.update({
    where: { id: lockId },
    data: {
      status:      LockStatus.WITHDRAWN,
      withdrawnAt: new Date(),
      txHashUnlock: txHash,
    },
  })
}

export async function getListingStats() {
  const [byTier, byStatus, totalLocked] = await Promise.all([
    prisma.tokenListing.groupBy({
      by:     ['tier'],
      _count: { id: true },
    }),
    prisma.tokenListing.groupBy({
      by:     ['status'],
      _count: { id: true },
    }),
    prisma.liquidityLock.aggregate({
      where:  { status: LockStatus.LOCKED },
      _sum:   { lunesLocked: true },
      _count: { id: true },
    }),
  ])

  return {
    byTier,
    byStatus,
    totalLockedLunes: totalLocked._sum.lunesLocked?.toString() ?? '0',
    totalActiveLocks: totalLocked._count.id,
  }
}
